#
# Module manifest for module 'AmznFailoverCluster'
#
# Generated by: Andrew Pearce
#
# Generated on: 3/12/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'AmznFailoverCluster.psm1'

# Version number of this module.
ModuleVersion = '2.6'

# ID used to uniquely identify this module
GUID = '91fb3f87-145e-4239-bcda-4d07dadb17b2'

# Author of this module
Author = 'Andrew Pearce'

# Company or vendor of this module
CompanyName = 'Amazon Web Services'

# Copyright statement for this module
Copyright = '(c) 2017 Amazon Web Services. All rights reserved.'

# Description of the functionality provided by this module
Description = 'DSC Resource to build and manage Microsoft Failover Clusters built in AWS Auto Scaling Groups. Based off the community xFailOverCluster.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Functions to export from this module
# FunctionsToExport = '*'

# Cmdlets to export from this module
# CmdletsToExport = '*'

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = '*'

# DSC resources to export from this module
DscResourcesToExport = 'ASGFailoverCluster','ClusterAccess','ClusterCleanup','ClusterClientAccessPoint','ClusterGroup','ClusterIPAddressResource','IsNotClusterOwner','ServiceResource'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('DesiredStateConfiguration', 'DSC', 'DSCResource', 'AWS')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://code.amazon.com/packages/Corpsys-Core-DSC-AMZN-FailoverCluster/trees/mainline'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '
2.2: Initial release
2.3: Added dsacls command to auto configure Failover Cluster Objects security permissions
2.5: Added support to enable UseNetworkName for Service Resources
'

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

